services:
  watchflix-addon:
    build: .
    image: watchflix-devstreamz-addon:latest
    container_name: watchflix-devstreamz-addon
    ports:
      - "7000:7000"
    env_file:
      - .env
    restart: unless-stopped
